#!/usr/bin/env python

import sys

with open("illum/__init__.py") as f:
    content = f.read()
line = content.split("\n")[0]
version = line.split("=")[1].strip().strip("\"'")

with open(sys.argv[1]) as f:
    content = f.read()

with open(sys.argv[1], "w") as f:
    f.write(version + ": " + content)
