#!/usr/bin/env python

from datetime import datetime as dt
from git import Repo
import re

repo = Repo('.')

tracked_list = ["version","illumina.f","setup.py","main.py"]

with open("version") as f:
    old = f.read().strip()
new = '.'.join(old.split('.')[:2])

new += '.' + dt.now().strftime("%gw%V.%u")
new += 'a' if new != old.split('-')[0][:-1] \
    else chr(ord(old.split('-')[0][-1])+1)

branch = repo.active_branch.name
if branch != "master":
    new += "-" + branch

for fname in tracked_list:
    with open(fname) as f:
        file_content = f.read()
    with open(fname,'w') as f:
        f.write(file_content.replace(old,new))
    repo.git.add(fname)

