#!/usr/bin/env python3

from datetime import datetime as dt

from git import Repo

repo = Repo(".")

with open("illum/__init__.py") as f:
    content = f.read()
line = content.split("\n")[0]
version = line.split("=")[1].strip().strip("\"'")

parts = version.split(".")[:3]

if repo.active_branch.name == "master":
    parts[2] = str(int(parts[2]) + 1)
else:
    parts.append(dt.utcnow().strftime("%Y%m%d.%H%M%S%f")[:-4])

with open("illum/__init__.py", "w") as f:
    f.write(content.replace(version, ".".join(parts)))
repo.git.add("illum/__init__.py")
