#!/bin/bash
echo "************************************************"
echo "*                                              *"
echo "*                    cmbps                     *"
echo "*                                              *"
echo "*           Combining two PSD files            *"
echo "*                                              *"
echo "*     Martin Aube 2000                         *"
echo "*                                              *"
echo "************************************************"
echo " "
folder=`pwd`
rm -f core
echo " Experiment directory "$folder
ls *.psd
ln -s $HOME/svn/illumina/trunk/bin/cmbpsd cmbpsd
echo " Executing cmbpsd..."
./cmbpsd
echo " Deleting temporary files in " $folder
rm -f cmbpsd
if [ -f core ] 
   then   echo "******** An error occured during execution of cmbps! ********"
   rm -f core
   echo "Hit <CTRL-c> or <CRTL-z> to kill that process"
   read bidon
else
  echo " Normal end of cmbps." 
fi 

