#!/bin/bash
echo "************************************************"
echo "*                                              *"
echo "*                     mkimi                    *"
echo "*                                              *"
echo "*         Edit input file for imies.f          *"
echo "*                                              *"
echo "*     Martin Aube 2000                         *"
echo "*                                              *"
echo "************************************************"
echo " "
folder=`pwd`
rm -f core
echo " Experiment directory "$folder
ln -s $HOME/svn/illumina/trunk/bin/MakeMieIn MakeMieIn
echo " Executing MakeMieIn..."
./MakeMieIn
echo " Deleting temporary files in " $folder
rm -f MakeMieIn
if [ -f core ] 
   then   echo "******** An error occured during execution of mkimi! ********"
   rm -f core
   echo "Hit <CTRL-c> or <CRTL-z> to kill that process"
   read bidon
else
  echo " Normal end of mkimi." 
fi
